# Generated by Django 3.0.8 on 2022-08-20 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_delete_user_region'),
        ('account', '0003_auto_20220817_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Region',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Base')),
                ('region', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Region')),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Profile')),
            ],
            bases=('main.base',),
        ),
    ]
