# Generated by Django 3.0.8 on 2022-08-20 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20220820_1328'),
        ('account', '0004_user_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='kakao_region',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Region'),
        ),
    ]
