# Generated by Django 3.0.8 on 2022-08-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_kakao_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
    ]
