version: '3'
services:

  web:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn dnd_7th_4_backend.wsgi:application --bind 0.0.0.0:8000 --timeout=120
    environment:
      DJANGO_SETTINGS_MODULE: dnd_7th_4_backend.settings.prod
      TZ: "Asia/Seoul"
    env_file:
      - .env
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    expose:
      - 8000
    entrypoint:
      - sh
      - config/docker/entrypoint.prod.sh

  nginx:
    container_name: nginx
    build: ./config/nginx
    environment:
      TZ: "Asia/Seoul"
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    ports:
      - "80:80"
    depends_on:
      - web


  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7-alpine
    environment:
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - TZ=Asia/Seoul
    ports:
      - "5672:5672" # Default Port
      - "15672:15672" # For UI
    expose:
      - "15672"


  celery_worker:
    container_name: celery_worker
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports: []
    environment:
      TZ: "Asia/Seoul"
    depends_on:
      - web
      - rabbitmq
    command: sh -c "celery -A dnd_7th_4_backend worker --loglevel=info"

  celery_beat:
    container_name: celery_beat
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports: []
    environment:
      TZ: "Asia/Seoul"
    depends_on:
        - web
        - rabbitmq
        - celery_worker
    command: sh -c "celery -A dnd_7th_4_backend beat --loglevel=info"


volumes:
  static:
  media: