# Generated by Django 3.0.8 on 2022-08-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=10)),
                ('div_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('cor_x', models.IntegerField()),
                ('cor_y', models.IntegerField()),
                ('lon_h', models.IntegerField()),
                ('lon_m', models.IntegerField()),
                ('lon_s', models.FloatField()),
                ('lat_h', models.IntegerField()),
                ('lat_m', models.IntegerField()),
                ('lat_s', models.FloatField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('api4_code', models.CharField(max_length=10)),
                ('api5_code', models.CharField(max_length=8)),
                ('api6_code', models.CharField(max_length=8)),
                ('api10_code', models.IntegerField()),
            ],
        ),
    ]
