# Generated by Django 3.0.8 on 2022-08-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='api4_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='region',
            name='api5_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='region',
            name='api6_code',
            field=models.CharField(max_length=20),
        ),
    ]
