# Generated by Django 3.0.8 on 2022-08-09 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220808_0404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Api1',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Base')),
                ('base_date', models.CharField(max_length=10)),
                ('base_time', models.CharField(max_length=10)),
                ('PTY', models.CharField(max_length=10)),
                ('REH', models.CharField(max_length=10)),
                ('RN1', models.CharField(max_length=10)),
                ('T1H', models.CharField(max_length=10)),
                ('UUU', models.CharField(max_length=10)),
                ('VEC', models.CharField(max_length=10)),
                ('VVV', models.CharField(max_length=10)),
                ('WSD', models.CharField(max_length=10)),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Region')),
            ],
            bases=('main.base',),
        ),
    ]
