# Generated by Django 3.0.8 on 2022-08-08 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220809_0248'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='API6',
            new_name='Api_6',
        ),
    ]
