# Generated by Django 3.0.8 on 2022-08-12 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220810_0334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api2',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Base')),
                ('info_0', models.TextField()),
                ('info_1', models.TextField()),
                ('info_2', models.TextField()),
                ('info_3', models.TextField()),
                ('info_4', models.TextField()),
                ('info_5', models.TextField()),
                ('info_6', models.TextField()),
                ('info_7', models.TextField()),
                ('info_8', models.TextField()),
                ('info_9', models.TextField()),
                ('info_10', models.TextField()),
                ('info_11', models.TextField()),
                ('info_12', models.TextField()),
                ('info_13', models.TextField()),
                ('info_14', models.TextField()),
                ('info_15', models.TextField()),
                ('info_16', models.TextField()),
                ('info_17', models.TextField()),
                ('info_18', models.TextField()),
                ('info_19', models.TextField()),
                ('info_20', models.TextField()),
                ('info_21', models.TextField()),
                ('info_22', models.TextField()),
                ('info_23', models.TextField()),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Region')),
            ],
            bases=('main.base',),
        ),
    ]
