# Generated by Django 3.0.8 on 2022-08-09 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220809_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api_7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sunrise', models.IntegerField()),
                ('sunset', models.IntegerField()),
                ('region_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Region')),
            ],
        ),
    ]
