# Generated by Django 3.0.8 on 2022-08-12 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_api4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api5',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Base')),
                ('regId', models.CharField(max_length=20)),
                ('tmFc', models.CharField(max_length=20)),
                ('taMin3', models.CharField(max_length=10)),
                ('taMax3', models.CharField(max_length=10)),
                ('taMin4', models.CharField(max_length=10)),
                ('taMax4', models.CharField(max_length=10)),
                ('taMin5', models.CharField(max_length=10)),
                ('taMax5', models.CharField(max_length=10)),
                ('taMin6', models.CharField(max_length=10)),
                ('taMax6', models.CharField(max_length=10)),
                ('taMin7', models.CharField(max_length=10)),
                ('taMax7', models.CharField(max_length=10)),
                ('taMin8', models.CharField(max_length=10)),
                ('taMax8', models.CharField(max_length=10)),
                ('taMin9', models.CharField(max_length=10)),
                ('taMax9', models.CharField(max_length=10)),
                ('taMin10', models.CharField(max_length=10)),
                ('taMax10', models.CharField(max_length=10)),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Region')),
            ],
            bases=('main.base',),
        ),
    ]
