# Generated by Django 3.0.8 on 2022-08-12 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_api5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('today_sunrise', models.IntegerField()),
                ('today_sunset', models.IntegerField()),
                ('tomorrow_sunrise', models.IntegerField(default=0, null=True)),
                ('tomorrow_sunset', models.IntegerField(default=0, null=True)),
                ('region_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Api8',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Base')),
                ('today', models.IntegerField()),
                ('tomorrow', models.IntegerField()),
                ('div_code', models.CharField(max_length=10)),
            ],
            bases=('main.base',),
        ),
        migrations.CreateModel(
            name='Api9',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Base')),
                ('temperature', models.CharField(default='', max_length=1500, null=True)),
                ('base_time', models.CharField(default='', max_length=10, null=True)),
                ('div_code', models.CharField(max_length=10)),
            ],
            bases=('main.base',),
        ),
        migrations.RenameModel(
            old_name='Api_6',
            new_name='Api6',
        ),
        migrations.DeleteModel(
            name='Api_7',
        ),
    ]
