# Generated by Django 3.0.8 on 2022-08-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220812_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='api3',
            name='info_48',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AddField(
            model_name='api3',
            name='info_49',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AddField(
            model_name='api3',
            name='info_50',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AddField(
            model_name='api3',
            name='info_51',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AddField(
            model_name='api3',
            name='info_52',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AddField(
            model_name='api3',
            name='info_53',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AddField(
            model_name='api3',
            name='info_54',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AddField(
            model_name='api3',
            name='info_55',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AddField(
            model_name='api3',
            name='info_56',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AddField(
            model_name='api3',
            name='info_57',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AddField(
            model_name='api3',
            name='info_58',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AddField(
            model_name='api3',
            name='info_59',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AddField(
            model_name='api3',
            name='info_60',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AddField(
            model_name='api3',
            name='info_61',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AddField(
            model_name='api3',
            name='info_62',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AddField(
            model_name='api3',
            name='info_63',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AddField(
            model_name='api3',
            name='info_64',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AddField(
            model_name='api3',
            name='info_65',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AddField(
            model_name='api3',
            name='info_66',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AddField(
            model_name='api3',
            name='info_67',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AddField(
            model_name='api3',
            name='info_68',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AddField(
            model_name='api3',
            name='info_69',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AddField(
            model_name='api3',
            name='info_70',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AddField(
            model_name='api3',
            name='info_71',
            field=models.TextField(default=' ', null=True),
        ),
    ]
