# Generated by Django 3.0.8 on 2022-08-14 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220813_0409'),
        ('main', '0010_auto_20220813_1653'),
    ]

    operations = [
    ]
