# Generated by Django 3.0.8 on 2022-08-17 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220816_2151'),
        ('main', '0011_merge_20220814_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Region',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Base')),
                ('region', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Region')),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Profile')),
            ],
            bases=('main.base',),
        ),
    ]
