# Generated by Django 3.0.8 on 2022-08-19 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_user_region'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Region',
        ),
    ]
