# Generated by Django 3.0.8 on 2022-08-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Humidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('imageUrl', models.TextField(max_length=100)),
                ('standard', models.CharField(choices=[('1', '습함'), ('2', '쾌적'), ('3', '건조')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Precipitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('imageUrl', models.TextField(max_length=100)),
                ('standard', models.CharField(choices=[('1', '강수없음'), ('2', '약한 비'), ('3', '보통 비'), ('4', '강한 비'), ('5', '매우 강한 비')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('imageUrl', models.TextField(max_length=100)),
                ('standard', models.CharField(choices=[('1', '4미만'), ('2', '4이상 ~ 9미만'), ('3', '9이상 ~ 14미만'), ('4', '14이상')], max_length=50)),
            ],
        ),
    ]
