# Generated by Django 3.0.8 on 2022-08-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Today',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('first_standard', models.CharField(max_length=50)),
                ('second_standard', models.CharField(default='', max_length=50, null=True)),
                ('season', models.CharField(choices=[('1', '봄'), ('2', '여름'), ('3', '가을'), ('4', '겨울')], max_length=10)),
            ],
        ),
    ]
