# Generated by Django 3.0.8 on 2022-08-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='today',
            name='first_standard',
            field=models.IntegerField(),
        ),
    ]
