# Generated by Django 3.0.8 on 2022-08-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_finedust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finedust',
            name='standard',
            field=models.CharField(choices=[('1', '좋음, 보통'), ('2', '나쁨'), ('3', '매우 나쁨')], max_length=50),
        ),
    ]
