# Generated by Django 3.0.8 on 2022-08-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_auto_20220815_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Windchill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('imageUrl', models.TextField(max_length=100)),
                ('standard', models.CharField(choices=[('1', '여름철 관심'), ('2', '여름철 주의'), ('3', '여름철 경고'), ('4', '여름철 위험'), ('5', '겨울철 낮음'), ('6', '겨울철 보통'), ('7', '겨울철 추움'), ('8', '겨울철 주의'), ('9', '겨울철 위험')], max_length=50)),
            ],
        ),
    ]
