# Generated by Django 3.0.8 on 2022-08-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_auto_20220820_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finedust',
            name='standard',
            field=models.CharField(choices=[('1', '좋음'), ('2', '보통'), ('3', '나쁨'), ('4', '매우 나쁨')], max_length=50),
        ),
    ]
