# Generated by Django 3.0.8 on 2022-08-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0009_auto_20220820_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windchill',
            name='standard',
            field=models.CharField(choices=[('0', '문제없음'), ('1', '여름철 문제없음'), ('2', '여름철 관심'), ('3', '여름철 주의'), ('4', '여름철 경고'), ('5', '여름철 위험'), ('6', '겨울철 낮음'), ('7', '겨울철 보통'), ('8', '겨울철 추움'), ('9', '겨울철 주의'), ('10', '겨울철 위험')], max_length=50),
        ),
    ]
