# Generated by Django 3.0.8 on 2022-08-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0011_auto_20220823_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finedust',
            name='imageUrl',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='humidity',
            name='imageUrl',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='precipitation',
            name='imageUrl',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='wind',
            name='imageUrl',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='windchill',
            name='imageUrl',
            field=models.TextField(),
        ),
    ]
